### PR TITLE
Migrate to multiplatform

### PR DESCRIPTION
**Pull request by Dominaezzz**
So I've setup a multiplatform project with only a JVM target for now.
I expect we'll gradually move components to the common source set .... until we can't.
Then we'll look at viable abstractions.

There's one tiny gotcha. The play button IntelliJ offers when looking at a sample file won't work anymore because of a bug in IntelliJ (about resource handling) we discussed.
So I've created a gradle task for each sample to run them.

### CODE REVIEW

**Comment by markaren** [comment]
Will check it out!

**Comment by markaren** [comment]
First the IDE was not able to find any three.kt classes. Everything red. This I fixed by selecting the "use separate modules per source sets" option. However, I can't run the examples either through run file or using the tasks you made. I get `Error: Could not find or load main class ...`

**Comment by markaren** [comment]
I could push #29 forward to (partly) resolve the resource issue

**Comment by Dominaezzz** [comment]
Hmm, I did `gradle clean` then `gradle runBasicSample` and it still works.
Can I see the full output of the two commands?

**Comment by markaren** [comment]
```
Task :examples:runBasicExample FAILED
Error: Could not find or load main class info\laht\threekt\BasicExample
Caused by: java.lang.NoClassDefFoundError: info/laht/threekt/BasicExample (wrong name: info\laht\threekt\BasicExample)
Error: Could not find or load main class info\laht\threekt\BasicExample



Caused by: java.lang.NoClassDefFoundError: info/laht/threekt/BasicExample (wrong name: info\laht\threekt\BasicExample)
```

Running with `--stacktrace` crashes. Dunno if that's related.

**Comment by Dominaezzz** [comment]
Oh, you're not on Linux. I made a terrible assumption about path separators. :sweat_smile:

**Comment by markaren** [comment]
That was better!

**Comment by markaren** [comment]
With the README update I pushed I think we can merge this and slowly improve it.

**Pull request merged**
