### PR TITLE
Make it possible to create custom mouse events

### LINKED ISSUE #62: Can't implement mouse events in `PeripheralsEventSource`
I want to set a custom `PeripheralsEventSource` for my orbit controls, but I can't create a new mouse event. One method there is internal and all the setters are private.

Allow us to implement our own `PeripheralsEventSource` please. I only want to enable `OrbitControls` within my `cuchaz.jfxgl.controls.OpenGLPane`.

### PR DESCRIPTION
**Pull request by markaren**
Looks ok @Displee ?

Closes #62

### CODE REVIEW

**Comment by Displee** [comment]
Almost perfect. I've created a JavaFX implementation for any node which extends the `Region` class (which are almost all existing controls) which looks like this:
```kotlin
package info.laht.threekt.examples.javafx

import info.laht.threekt.WindowSize
import info.laht.threekt.input.*
import javafx.event.EventHandler
import javafx.scene.input.KeyEvent
import javafx.scene.input.MouseButton
import javafx.scene.input.MouseEvent
import javafx.scene.input.ScrollEvent
import javafx.scene.layout.Region

class FXNodeEventsSource(private val node: Region) : PeripheralsEventSource {

    val mappedMouseListeners = mutableMapOf<MouseListener, Array<EventHandler<*>>>()
    val mappedKeyListeners = mutableMapOf<KeyListener, EventHandler<KeyEvent>>()

    override val size: WindowSize
        get() = WindowSize(node.width.toInt(), node.height.toInt())

    override fun addKeyListener(listener: KeyListener) {
        val eventHandler = EventHandler { it: KeyEvent ->
            listener.onKeyPressed(KeyEvent(it.code.impl_getCode(), KeyAction.PRESS))
        }
        mappedKeyListeners[listener] = eventHandler
        node.addEventHandler(KeyEvent.KEY_PRESSED, eventHandler)
    }

    override fun addMouseListener(listener: MouseListener) {
        val mouseMoveEventHandler = EventHandler { it: MouseEvent ->
            val event = object: info.laht.threekt.input.MouseEvent {
                override val clientX: Int
                    get() = it.screenX.toInt()

                override val clientY: Int
                    get() = it.screenY.toInt()
            }
            listener.onMouseMove(event)
        }
        val mouseUpEventHandler = EventHandler { it: MouseEvent ->
            val event = object: info.laht.threekt.input.MouseEvent {
                override val clientX: Int
                    get() = it.screenX.toInt()

                override val clientY: Int
                    get() = it.screenY.toInt()
            }
            listener.onMouseUp(fxButtonToThree(it.button), event)
        }
        val mouseDownEventHandler = EventHandler { it: MouseEvent ->
            val event = object: info.laht.threekt.input.MouseEvent {
                override val clientX: Int
                    get() = it.screenX.toInt()

                override val clientY: Int
                    get() = it.screenY.toInt()
            }
            listener.onMouseDown(fxButtonToThree(it.button), event)
        }
        node.addEventHandler(MouseEvent.MOUSE_DRAGGED, mouseMoveEventHandler)
        node.addEventHandler(MouseEvent.MOUSE_RELEASED, mouseUpEventHandler)
        node.addEventHandler(MouseEvent.MOUSE_PRESSED, mouseDownEventHandler)

        val scrollEventHandler = EventHandler { it: ScrollEvent ->
            val mouseWheelEvent = object: MouseWheelEvent {
                override val deltaX: Float
                    get() = it.deltaX.toFloat()
                override val deltaY: Float
                    get() = -it.deltaY.toFloat()
            }
            listener.onMouseWheel(mouseWheelEvent)
        }
        node.addEventHandler(ScrollEvent.SCROLL, scrollEventHandler)

        mappedMouseListeners[listener] = arrayOf(mouseMoveEventHandler, mouseUpEventHandler, mouseDownEventHandler, scrollEventHandler)
    }

    override fun removeKeyListener(listener: KeyListener): Boolean {
        val eventHandler = mappedKeyListeners.remove(listener) ?: return false
        node.removeEventHandler(KeyEvent.KEY_PRESSED, eventHandler)
        return true
    }

    override fun removeMouseListener(listener: MouseListener): Boolean {
        val eventHandlers = mappedMouseListeners.remove(listener) ?: return false
        val mouseHandler = eventHandlers[0] as EventHandler<MouseEvent>
        val mouseUpHandler = eventHandlers[1] as EventHandler<MouseEvent>
        val mouseDownHandler = eventHandlers[2] as EventHandler<MouseEvent>
        val mouseWheelHandler = eventHandlers[3] as EventHandler<ScrollEvent>
        node.removeEventHandler(MouseEvent.MOUSE_DRAGGED, mouseHandler)
        node.removeEventHandler(MouseEvent.MOUSE_RELEASED, mouseUpHandler)
        node.removeEventHandler(MouseEvent.MOUSE_PRESSED, mouseDownHandler)
        node.removeEventHandler(ScrollEvent.SCROLL, mouseWheelHandler)
        return true
    }

    //TODO Should make OrbitControls.MouseButtons class public so we can reference it instead of these magic numbers
    fun fxButtonToThree(button: MouseButton): Int {
        return when(button) {
            MouseButton.NONE -> -1
            MouseButton.PRIMARY -> 0
            MouseButton.MIDDLE -> 2
            MouseButton.SECONDARY -> 1
        }
    }

}
```
It works very well. You may include this in the examples. You can make `MouseButton` public so I can ditch the random numbers in the last function.

Anyhow. This update has a huge impact. Now I can use my `OrbitControls` only inside my render area. Which makes other JavaFX controls usable. I'm not messing up my meshes while I click or scroll through a `ListView` anymore :).

Thanks a lot!

**Comment by markaren** [comment]
You say "Almost perfect". Are you referring to the MouseButton integers values?

**Comment by markaren** [comment]
For any changes to the examples, I'd rather you provide a PR.

**Comment by Displee** [comment]
Yeah that's correct. The `MouseButtons` was the only thing. I'll create a new pr when I have time with a new example then.

**Comment by markaren** [comment]
Merging this. Might revisit `MouseButtons` later.

**Pull request merged**
