### PR TITLE
Feature/add instanced mesh

### PR DESCRIPTION
**Pull request by Displee**
With `InstancedMesh` we can render the same geometry thousands of times with only 1 draw call. This is a big performance boost :)
I've implemented this example: https://threejs.org/examples/webgl_instancing_raycast

CVyMBz8WsF

Since r106 didn't have this feature, I ripped it from the last threejs release (r125).

### CODE REVIEW

**Comment by Displee** [comment]
For some odd reason the `HemisphereLight`s in the example doesn't cast any light. I'm using a custom color (`whitesmoke`) for the geometries, but that shouldn't be needed.  Should I create an issue for this?

**Comment by markaren** [comment]
> For some odd reason the HemisphereLights in the example doesn't cast any light.

But it does? removing one of the lights clearly alters the perceived color of the spheres

**Comment by markaren** [comment]
Nice work btw

**Comment by Displee** [comment]
> > For some odd reason the HemisphereLights in the example doesn't cast any light.
> 
> But it does? removing one of the lights clearly alters the perceived color of the spheres

Well. The geometries should turn white like in the original example without the custom 'whitesmoke' color. If I remove the 'whitesmoke' color the geometries will turn black instead of white.

**Comment by markaren** [comment]
Aight, I see what is happening.
In three.kt Color() -> black (0,0,0)
In three.js Color() -> white(1,1,1)

**Comment by markaren** [comment]
Pushed a fix to master. Default rgb color is now white, not black

**Comment by Displee** [comment]
Ah, good job.

**Pull request merged**
