### PR TITLE
Move math classes to common.

### PR DESCRIPTION
**Pull request by Dominaezzz**
Moved all the math classes to common.
Some of the functions had dependencies on jvm stuff or more complicated classes, so I made them extension functions for now.
We can move them back to members once we move most of the codebase.

Although, I'd argue we should leave them as extensions but java ease-of-use :man_shrugging: .

### CODE REVIEW

**Comment by markaren** [comment]
I would suggest that we move everything buffer related into the buffer class(es) themselves. The `BufferAttribute` is probably the only problematic class outside the `renderers` package wrt multiplatform. This way we contain it, and we don't have to use extension functions. The other functions that you put as extensions here are functions that eventually should go back to where they where.

**Comment by Dominaezzz** [comment]
By buffer classes, I assume you're taking about the `FloatBufferAttribute` classes?

**Comment by markaren** [comment]
Yes, the float and intbufferattribute classes

**Comment by markaren** [comment]
One more thing. I guess we should be consistent with how equals are implemented.
Now both 
```kotlin
if (other !is Line3) return false
```
and
```kotlin
  if (other == null || this::class != other::class) return false

  other as Line3
```

are used. The latter is generated by IntelliJ. So I guess we should use that one?

**Comment by Dominaezzz** [comment]
I wrote both myself.
I went with the second one at first but I changed to the first one, since it's shorter (and easier to read IMHO).
The first one is a bit better for Native I think, since it has less reflection-esque code.

**Comment by markaren** [comment]
The first one will also return true for descendants for that class (with the same fields), while the other will not.

**Comment by Dominaezzz** [comment]
Ah I see. It's kinda wrong.
Although, the classes are final by default, so there will be no descendants :stuck_out_tongue: .
I think we should just go with data classes and leave this to the language.

**Comment by markaren** [comment]
I'm fine with that. Actually from the API point of view we are just adding a extra copy function. The original copy and clone can still remain. The clone has to be there as we check for `clonable` instances elsewhere.

**Comment by Dominaezzz** [comment]
Speaking of which, we should probably make the `Cloneable` interface generic at some point.

**Review by markaren — APPROVED** [review]

**Pull request merged**
